name: web_frontend
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  share_plus: ^7.2.1
  file_picker: ^5.0.1
  flutter_cache_manager: ^3.3.0
  firebase_messaging: ^14.8.0
  firebase_core: ^2.16.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  http_parser: ^4.0.0
  image_picker: ^0.8.6+3
  provider: ^6.0.5
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.5.0
  syncfusion_flutter_pdfviewer: ^20.3.56
  shared_preferences: ^2.0.9
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.3
  http: ^0.13.4
  cached_network_image: ^3.2.0



dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.jpg
    - assets/icons/img1.jpg
    - assets/icons/img2.jpg
    - assets/icons/img3.jpg
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/apple.png
    - assets/icons/login.png
    - assets/icons/signup.png

  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
          weight: 200
